### ISSUE TITLE
Rabbit短信登陆问题

### ISSUE THREAD

**Issue by mike9755** [djun90/hh_bncr_plugins#1]
你好，短信登陆的时候提示Method POST not allowed for URL /api/sendSMS怎么处理呢
![image](https://github.com/djun90/hh_bncr_plugins/assets/5673534/382f3fb4-cb07-4d71-9f64-282b158aa901)

**Comment by djun90** [comment]
看看网页正常不吧，记得把兔子容器里的apiToken删除

**Comment by djun90** [comment]
..
